### ISSUE TITLE
ESPN Projections Overall and Position Ranks Not Applied Correctly

### ISSUE THREAD

**Issue by bpafoshizle** [dadrivr/FantasyFootballAnalyticsR#13]
I'm running R version 3.1.2 (2014-10-31) on x86_64-apple-darwin13.4.0. 

It looks like the cause is the order function is sorting characters, rather than numerics, so at some point, the as.numeric function needs to be applied to the points field. See line 129 and 132 of the "ESPN Projections.R" file.

Simple solution: 
`projections_espn <- projections_espn[order(-as.numeric(points))][,overallRank := 1:.N]`

This problem is causing Geno Smith to be ranked the top QB. :)

**Comment by dadrivr** [comment]
We're currently working on the Auction tool so we haven't been able to keep the scripts on the repo up-to-date.  This is on our to-do list, though: Issue https://github.com/dadrivr/FantasyFootballAnalyticsR/issues/11.  Thanks!

-Isaac

**Comment by dadrivr** [comment]
This is fixed with our new ffanalytics R package:
http://fantasyfootballanalytics.net/2016/06/ffanalytics-r-package-fantasy-football-data-analysis.html

Thanks!
-Isaac
