### ISSUE TITLE
projections_fp

### ISSUE THREAD

**Issue by mee218** [dadrivr/FantasyFootballAnalyticsR#16]
I get this error when trying to run the "FantasyPros Projections.R" 

Error in `$<-.data.frame`(`*tmp*`, "positionRank_fp", value = 0) : 
  replacement has 1 row, data has 0

**Comment by dadrivr** [comment]
This is fixed with our new ffanalytics R package:
http://fantasyfootballanalytics.net/2016/06/ffanalytics-r-package-fantasy-football-data-analysis.html

Thanks!
-Isaac
