### ISSUE TITLE
Invalid Command Name "toplevel"

### ISSUE THREAD

**Issue by cwall0868** [dadrivr/FantasyFootballAnalyticsR#24]
Tried running scrape a few times with no luck. 

OS: OSX
Using RStudio: 0.99.893
R Version: 3.3.3
Sample Input:
```
myProjections <- getProjections(scrapeData=runScrape(week = 0, season = 2016, analysts = c(-1, 3, 4, 5, 6, 7, 8, 9, 17, 18, 19, 20, 25, 26, 27), positions = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB")), avgMethod = "robust", leagueScoring = userScoring, vorBaseline, vorType, teams = 12, format = "standard", mflMocks = 1, mflLeagues = 1, adpSources = c("CBS", "ESPN", "FFC", "MFL", "NFL", "Yahoo"))`
```
Error Returned:
```
Error in structure(.External(.C_dotTclObjv, objv), class = "tclObj") : 
  [tcl] invalid command name "toplevel".
```

I played around with a few options in the config to see if it had something to do with the lack of data available this early, but didn't have any luck getting it to run. 

It seems like I was able to sucessfully pull data.
<img width="1328" alt="rstudio_player_data_table" src="https://cloud.githubusercontent.com/assets/1831549/16179376/b92ddfb2-3631-11e6-8511-f13863deefb2.png">

**Comment by dadrivr** [comment]
I'm not able to replicate with my Mac.  Could you send your 'userScoring' settings, so we can try to replicate?

**Comment by dadrivr** [comment]
I'm closing this issue because we have not heard back in the last 2 weeks.  If it's still not fixed, please let us know.

**Comment by christran21** [comment]
I just ran into the same issue. I followed your steps from June 19 but the issue was not solved. 

`myProjections <- getProjections(scrapeData=runScrape(week = 0, season = 2016, analysts = c(-1, 3, 4, 5, 6, 7, 9, 17, 18, 19, 20, 28), positions = c("QB", "RB", "WR", "TE", "K", "DST")), avgMethod = "average", leagueScoring = userScoring, vorBaseline, vorType, teams = 12, format = "standard", mflMocks = -1, mflLeagues = -1, adpSources = NULL)
Error: could not find function "getProjections"`

**Comment by dadrivr** [comment]
Make sure you've loaded the package with `library("ffanalytics")`.  If that doesn't work, try this:
http://fantasyfootballanalytics.net/2016/06/ffanalytics-r-package-fantasy-football-data-analysis.html#comment-17635

**Comment by cwall0868** [comment]
i was able to get this working.. you might double check and make sure you have installed/loaded rstudioapi as well..

**Comment by cbroglie** [comment]
I hit this as well, and restarting my computer fixed it. I had not restarted my computer after installing XQuartz/R/RStudio before trying out this package.
