### ISSUE TITLE
runScrape scope problem

### ISSUE THREAD

**Issue by mtbowyer** [dadrivr/FantasyFootballAnalyticsR#25]
When trying to call runScrape after loading the ffanalytics and data.table packages, I get 'Error in duplicated(siteId) : Object 'siteId' not found.

Looking in R Package/ffanalytics/R at runScrape.R, it appears to be line 190.  I think it needs to be this:

periodAnalysts[duplicated(siteId), siteId]

instead of 

periodAnalysts$siteId[duplicated(siteId)]

For what it's worth, I'm using data.table 1.9.4 and R-3.2.0.

**Comment by dadrivr** [comment]
Thanks for letting us know.  We're not able to replicate.  Could you try upgrading data.table to the latest version (and possibly R)?  What OS are you using?

**Comment by mtbowyer** [comment]
A new version of data.table appeared to do the trick. I tried to find a change log to see if I could track down why, but wasn't able to find one.

Thanks!
