### ISSUE TITLE
R fatal error

### ISSUE THREAD

**Issue by dhardister** [dadrivr/FantasyFootballAnalyticsR#26]
Windows 7 32-bit, RStudio 0.99.902, R 3.3.1, Tried both admin and non-admin accounts

Installed R & RStudio & devtools. I did not install RStudioapi since it was installed under devtools.

Using "devtools::install_github(repo = "dadrivr/FantasyFootballAnalyticsR",  subdir = "R Package/ffanalytics")" to install the ffanalytics R package, this is returned "Downloading GitHub repo dadrivr/FantasyFootballAnalyticsR@master
from URL https://api.github.com/repos/dadrivr/FantasyFootballAnalyticsR/zipball/master". About a minute later, a window appears reading "R Session Aborted - R encountered a fatal error."

Please provide any solutions you may have.

**Comment by dhardister** [comment]
I tried all of the tarballs and received a statement concerning a non-zero exit status of 1. If you need the exact message, let me know and I can re-run the tarballs install and paste the message here.

I downloaded the ffanalytics directory into the RStudio library but the add-in is not recognized. Is there any way to brute force an add-in install?

**Comment by dadrivr** [comment]
Sorry for the difficulty!  We just uploaded a new tarball.  Could you try installing that one and post here what command you're using and what error you get?  If that doesn't work, and you have checked out the repo then you can build the package by `CTRL+SHIFT+B` from the ffanalytics project, i.e. use the `ffanalytics.Rproj` file in the ffanalytics root directory.

**Comment by dhardister** [comment]
The tarball error is
ERROR: dependencies 'shiny', 'miniUI', 'DT', 'Hmisc' are not available for package 'ffanalytics'
* removing 'C:/Users/bhardister/Documents/R/win-library/3.3/ffanalytics'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.1/bin/i386/R" CMD INSTALL -l "C:\Users\bhardister\Documents\R\win-library\3.3" "C:/Users/bhardister/Documents/R/ffanalytics_0.1.4.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/bhardister/Documents/R/ffanalytics_0.1.4.tar.gz’ had non-zero exit status

The build & restore package error is similar
* installing to library 'C:/Users/bhardister/Documents/R/win-library/3.3'
ERROR: dependencies 'shiny', 'miniUI', 'DT', 'Hmisc' are not available for package 'ffanalytics'
* removing 'C:/Users/bhardister/Documents/R/win-library/3.3/ffanalytics'

Exited with status 1.

I'm wondering whether it is because of R 3.3.1. Let me know if you have any other ideas.

**Comment by dadrivr** [comment]
What happens if you first install those packages listed (`shiny`, `miniUI`, `DT`, `Hmisc`)?

**Comment by dhardister** [comment]
Finally! Now I need to bang around in R & RStudio and figure out how to get
the data. Thanks for all of your help with this and making this available.
