### ISSUE TITLE
Trouble with running script IDP.R

### ISSUE THREAD

**Issue by timrizzi81** [dadrivr/FantasyFootballAnalyticsR#29]
Hi - Thanks for putting all of this together.  So, I've gotten to the point where it's having trouble with object.analyst and so, I'm walking through the Prepare Data.R Data scripts and running the first Ranking Script (the functions already successfully ran) and getting this error:

Error in IDP[, c("Player (team, bye)")] : incorrect number of dimensions
In addition: Warning message:
XML content does not seem to be XML: 'https://www.fantasypros.com/nfl/rankings/idp-cheatsheets.php'

**Comment by dadrivr** [comment]
Those scripts are out of date and not maintained.  If you want to scrape IDP projections, use the `ffanalytics` R package:
http://fantasyfootballanalytics.net/2016/06/ffanalytics-r-package-fantasy-football-data-analysis.html
