### ISSUE TITLE
Football outsiders support

### ISSUE THREAD

**Issue by sansbacon** [dadrivr/FantasyFootballAnalyticsR#31]
Can you provide support for .csv file from Football Outsiders? I've attached a sample of their format. If you have a list of columns that you need to make the import easier, I can write a script to transform their csv file to something that can be imported into ffanalytics

Thanks!

[football-outsiders-sample.csv.zip](https://github.com/dadrivr/FantasyFootballAnalyticsR/files/402681/football-outsiders-sample.csv.zip)

**Comment by dadrivr** [comment]
Here's how you can add other sources:
https://github.com/dadrivr/FantasyFootballAnalyticsR/wiki/Adding-Sources
