### ISSUE TITLE
Subscript out of bounds error

### ISSUE THREAD

**Issue by jlcbean** [dadrivr/FantasyFootballAnalyticsR#33]
When the Calculation Settings page loads, getting "Error: subscript out of bounds error" where the position tier values would appear. This occurs when any position other than QB is selected.

![image](https://cloud.githubusercontent.com/assets/4047800/17840673/41f0c21c-67db-11e6-986d-b65449058654.png)

Console error
Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    96: tag
    95: tags$input
    94: tag
    93: tags$div
    92: div
    91: textInput
    90: tag
    89: tags$div
    88: tag
    87: tags$div
    86: tag
    85: tags$div
    84: div
    83: column
    82: FUN
    81: lapply
    80: tagList
    79: tag
    78: tags$div
    77: div
    76: fluidRow
    75: FUN
    74: lapply
    73: vorUI
    72: renderUI
    71: func
    70: output$vorData
     3: shiny::runApp
     2: runGadget
     1: Run_Projection

**Comment by dadrivr** [comment]
Could you give us more info so we can reproduce?  What do you get when you run `sessionInfo()`?

**Comment by jlcbean** [comment]
Never mind, reloading the package in RStudio resolved the issue.
