### ISSUE TITLE
Running library(ffanalytics) from the source files?

### ISSUE THREAD

**Issue by maat7043** [dadrivr/FantasyFootballAnalyticsR#36]
I am having trouble finding resources on how to run files from the source.  I am currently running a custom R Script with R Studio's that looks a lot like the included league scoring example followed by scrapeProjections followed by getProjections. It work perfect when loading the package that you created, but I would like to begin writing my own code and want to be able to modify the source files.  So far:

1. Installed R (3.3.1 latest)
2. Installed Latest R Studios
3. Cloned the whole github repository to my computer
4. Open */FantasyFootballAnalyticsR/R Package/ffanalytics/ffanalytics.Rproj with R Studios

If I now open up my script file I created before what do I need to do to run it and have it find and load all of the Functions?

Ive been trying to emulate the Main.R file you created previously:

source(paste(getwd(),"/R Scripts/Functions/Functions.R", sep=""))
source(paste(getwd(),"/R Scripts/Functions/League Settings.R", sep=""))

Thanks for any help!!
Matt

**Comment by dadrivr** [comment]
Hi Matt,

The R scripts (excluding the R package) are out-of-date and not maintained.  We recommend using the ffanalytics R package instead:
http://fantasyfootballanalytics.net/2016/06/ffanalytics-r-package-fantasy-football-data-analysis.html

Hope that helps!
-Isaac
